# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EKVoiceText' do
   pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
   pod 'Firebase', '>= 2.5.1'
   pod "PagingMenuController"
   pod 'FoldingCell', '~> 0.8.1'
end

target 'EKVoiceTextTests' do

end

